version: "3.9"
services:
  langbro_backend:
    build:
      dockerfile: ci/docker/backend.Dockerfile
      context: ../../
    ports:
      - "8080:8080"
    container_name: langbro_backend
    depends_on:
      - langbro_neo4j
    restart: unless-stopped

  langbro_neo4j:
    image: neo4j:4.2.3-enterprise
    container_name: "langbro_neo4j"
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs     
      - $HOME/neo4j/plugins:/plugins
      # - ../../data:/var/lib/neo4j/import
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=$NEO4J_AUTH_USER/$NEO4J_AUTH_PASSWORD
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - dbms.security.procedures.unrestricted=apoc.*

networks:
  default:
    name: langbro_net
